pipeline{
    agent{
        docker {image 'node:16-alpine'}
    }
    stages{
        stage("Test"){
            steps{
                echo "========executing A========"
                sh 'node --version'
            }
        }
    }
}