pipeline{
    agent none
    stages{
        stage("Back-end") {
            agent {
                docker { 
                    image 'maven:3.8.1-adoptopenjdk-11'
                }
            }
            steps {
                echo "========executing A========"
                sh 'mvn --version'
            }
        }
        stage('Front-end') {
            agent {
                docker {
                    image 'node:16-alpine'
                }
            }
            steps {
                sh 'node --version'
            }
        }
    }
    post{
        always{
            echo "========always========"
        }
        success{
            echo "========pipeline executed successfully ========"
        }
        failure{
            echo "========pipeline execution failed========"
        }
    }
}